### ISSUE TITLE
Does the agent need to prove possession of the tailscale key?

### ISSUE THREAD

**Issue by evan2645** [jsiebens/spire-tailscale-plugin#1]
Really cool plugin! Thank you for sharing it 🤗 

From the readme and brief look at the code, it seems that the agent sends a public key and the server looks it up to verify its presence in tailscale .. however, public key is also public information and not expected to be private. It seems like the server should issue a challenge, and the agent should solve/sign this challenge in order to prove possession of the private key (example [here](https://github.com/spiffe/spire/blob/main/pkg/server/plugin/nodeattestor/x509pop/x509pop.go))? Tailscale may not allow for this kind of key usage ... 

Another (way more involved) option could be to send a tailscale handshake over the node attestation exchange, and let the server either terminate or observe it.

**Comment by jsiebens** [comment]
Hi @evan2645 

Thank you for the feedback! Much appreciated.

@apenwarr mentioned it on twitter as well, so I definitely have to have a closer look at improving this plugin.

**Comment by jsiebens** [comment]
It seems like the Tailscale team is also working on OIDC id-tokens for the Tailscale machines:
- https://github.com/tailscale/tailscale/blame/c88506caa678e03e0f965a6288fa7482d8fe5e67/tailcfg/tailcfg.go#L1790
- https://github.com/tailscale/tailscale/blob/3601b4353004714e2b2cbfb365da6cb928101ff2/client/tailscale/tailscale.go#L280

As for as I can see, it is still WIP and not available yet. 

When ready, I believe such an id token can be useful for improving this spire plugin.

**Comment by jsiebens** [comment]
release v0.2.0 is now using those OIDC tokens from Tailscale
